### ISSUE TITLE
/api/meal/meal

### ISSUE THREAD

**Issue by sbuljat** [isevo/RWA_prvidio#4]
- Ista primjedba kao kod Users API, nepotreban posljednji član "meal"
- Pri dodavanju novog jela dobijem poruku "Desk reserved", pretpostavljam da je to neispravna poruka?
- Što se događa ako ima jako puno jela? Jeste razmišljali o paginaciji ili pretraživanju jela po nazivu, rasponu cijena, itd.?

**Comment by isevo** [comment]
Desk reserved je slucajno ostalo kao poruka kad sam kopirala jedan dio koda.Probala sam napravitit paginaciju,ali nije islo,pa taj dio nisam napravila.
